[package]
name = "insightsx"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1.3"
bytes = "1.6"
rdkafka = { version = "0.36", features = ["tokio"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
tonic = "0.11"
prost = "0.12"
chrono = { version = "0.4", features = ["serde"] }
prometheus = "0.13"
