version: "3.8"

services:
  insightsx:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: insightx-logs
      GRPC_ADDRESS: 0.0.0.0:50051
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true" # clearly enables auto-create topic
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
